intigraf_laravel/routes/web.php
Route::get('/media/korlantas/{id}/{detail}/{idchild?}',array('as' => 'home.portfolio', 'uses' => 'HomeController@portfolio'));
Route::get('/media/type/{id}/{detail}/{idchild?}',array('as' => 'home.type', 'uses' => 'HomeController@portfolioType'));
Route::get('/page/rss/{id}/{page?}',array('as' => 'home.rss', 'uses' => 'HomeController@rss'));
Route::get('/cari',array('as' => 'home.search', 'uses' => 'HomeController@search'));


Route::group(['middleware' => ['auth']], function(){
Route::get('vrs-admin/brosur', 'GeneralController@subscription');
	Route::post('vrs-admin/brosur', 'GeneralController@subscribe');
	Route::resource('vrs-admin/aduan', 'AduanController');
	Route::get('vrs-admin/replyForm/{id}', ['as' => 'vrs-admin.aduan.replyForm', 'uses' => 'AduanController@replyForm']);
	Route::get('vrs-admin/aduan/{id}/delete', ['as' => 'vrs-admin.aduan.delete', 'uses'=>'AduanController@destroys']);
	Route::post('vrs-admin/reply/{id}', ['as' => 'vrs-admin.aduan.reply', 'uses' => 'AduanController@reply']);

	Route::get('vrs-admin/product/getAllAjax',array('as' => 'product.api.getall','uses' => 'ProductController@getAllAjax'));
	Route::get('vrs-admin/product/{product}/delete',array('as'=> 'product.delete','uses' => 'ProductController@destroy'));
	Route::resource('vrs-admin/product', 'ProductController');

	Route::get('vrs-admin/event/getAllAjax',array('as' => 'event.api.getall','uses' => 'EventController@getAllAjax'));
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');
Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'vrs-admin.gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
		Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'vrs-admin.gerai.delete','uses' => 'GeraiController@destroy'));
		Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'vrs-admin.gerai.featured','uses' => 'GeraiController@featured'));
		Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');
	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');
	
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'cctv.delete','uses' => 'CCTVController@destroy'));

	Route::resource('vrs-admin/theme', 'ThemeController');
	Route::get('vrs-admin/club/{club}/delete',array('as'=> 'club.delete','uses' => 'ClubController@destroy'));
	Route::resource('vrs-admin/club', 'ClubController');

	Route::get('vrs-admin/portfolio/enabled/{id}/{menu}',array('as'=> 'portfolio.enabled','uses' => 'PortfolioController@enabled'));
	Route::get('vrs-admin/portfolio/featured/{id}', array('as' => 'portfolio.featured','uses' => 'PortfolioController@featured'));
	Route::get('vrs-admin/portfolio/{menu}/delete',array('as'=> 'portfolio.delete','uses' => 'PortfolioController@destroy'));

	Route::get('vrs-admin/detailportfolio/{menu}/delete',array('as'=> 'detailportfolio.delete','uses' => 'DetailPortfolioController@destroy'));
	Route::resource('vrs-admin/detailportfolio', 'DetailPortfolioController');

	Route::get('vrs-admin/portfolio/getAllData',array('as' => 'portfolio.api.getall','uses' => 'PortfolioController@getAllData'));
	Route::resource('vrs-admin/portfolio', 'PortfolioController');

	Route::get('vrs-admin/menu/{menu}/delete',array('as'=> 'menu.delete','uses' => 'MenuController@destroy'));
	Route::resource('vrs-admin/menu', 'MenuController');
	Route::get('vrs-admin/menu/detail/{menu}/delete',array('as'=> 'menu.detail.delete','uses' => 'MenuDetailController@destroy'));
	Route::get('vrs-admin/menu/detail/getjson',array('as'=> 'menu.detail.getjson','uses' => 'MenuDetailController@getjson'));
	Route::resource('vrs-admin/menu/detail', 'MenuDetailController');

	Route::resource('vrs-admin/ujian', 'UjianController');
	Route::get('vrs-admin/ujian/{ujian}/delete',array('as'=> 'ujian.delete','uses' => 'UjianController@destroy'));

	Route::resource('vrs-admin/soal', 'SoalController');
	Route::get('vrs-admin/soal/{soal}/delete',array('as'=> 'soal.delete','uses' => 'SoalController@destroy'));

	Route::post('vrs-admin/general/upload',array('as' => 'general.upload', 'uses' => 'GeneralController@upload'));
	Route::resource('vrs-admin/general', 'GeneralController');

	Route::get('vrs-admin/contact/enabled/{id}',array('as' => 'contact.enabled', 'uses' => 'ContactController@enabled'));
	Route::get('vrs-admin/contact/{contact}/delete',array('as'=> 'contact.delete','uses' => 'ContactController@destroy'));
	Route::resource('vrs-admin/contact', 'ContactController');
	
	Route::resource('vrs-admin/dailycp', 'DailyCPController');

	Route::get('vrs-admin/rss/getAllAjax',array('as' => 'rss.api.getall','uses' => 'RssController@getAllAjax'));
	Route::get('vrs-admin/rss/{rss}/delete',array('as'=> 'rss.delete','uses' => 'RssController@destroy'));
	Route::resource('vrs-admin/rss', 'RssController');

	Route::get('vrs-admin/social/{social}/delete',array('as'=> 'social.delete','uses' => 'SocialController@destroy'));
	Route::resource('vrs-admin/social', 'SocialController');

	Route::get('vrs-admin/comment/{comment}/delete',array('as'=> 'comment.delete','uses' => 'CommentController@destroy'));
	Route::get('vrs-admin/comment/{comment}/approve/{on}',array('as'=> 'comment.approve','uses' => 'CommentController@approve'));
	Route::resource('vrs-admin/comment','CommentController');

	Route::get('vrs-admin/typeclub/{id}/delete',array('as'=> 'typeclub.delete','uses' => 'TypeClubController@destroy'));
	Route::resource('vrs-admin/typeclub','TypeClubController');

	Route::get('vrs-admin/portfoliocategory/getAllAjax',array('as' => 'portfoliocategory.api.getall','uses' => 'PortfolioCategoryController@getAllAjax'));

	//Route::get('vrs-admin/notification/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/notification/create',array('as'=> 'notification.create','uses' => 'NotificationController@create'));
	Route::resource('vrs-admin/notification', 'NotificationController');
	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');
	Route::get('vrs-admin/media/getMedia/{name}','MediaController@getMedia');
	Route::get('vrs-admin/media/{media}/delete',array('as'=> 'media.delete','uses' => 'MediaController@destroy'));
	
	Route::resource('vrs-admin/media', 'MediaController');
	
	Route::get('vrs-admin/file/getMedia/{name}','FileController@getMedia');
	//Route::post('vrs-admin/file/create',array('as'=> 'file.create','uses' => 'FileController@create'));
	Route::get('vrs-admin/file/{file}/delete',array('as'=> 'file.delete','uses' => 'FileController@destroy'));
	Route::get('vrs-admin/file/featured/{id}', array('as' => 'file.featured','uses' => 'FileController@featured'));
	Route::resource('vrs-admin/file', 'FileController');
	Route::resource('vrs-admin/log', 'LogController');

	Route::get('vrs-admin/video/getMedia/{name}','VideoController@getMedia');
	Route::get('vrs-admin/video/{video}/delete',array('as'=> 'video.delete','uses' => 'VideoController@destroy'));
	Route::get('vrs-admin/video/featured/{id}', array('as' => 'video.featured','uses' => 'VideoController@featured'));
	Route::resource('vrs-admin/video', 'VideoController');

intigraf_laravel/app/Http/Controllers/CCTVController.php
<?php namespace App\Http\Controllers;
/*
lapantiga.com | Web & Mobile App Developer. Jl. Gubeng Kertajaya 9C no.27 A Surabaya - Indonesia, +62.856.3437.495 */

use App\Http\Controllers\BasicController;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\MediaRequest;
use App\Media;
use File;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Storage;
use Session;
use Image;
use Input;
use DB;
use DateTime;

class CCTVController extends BasicController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	protected $path;
	function __construct() {
		$this->path = 'upload/media/';
	}
	public function index()
	{
		$data['content'] = DB::table('ms_cctv')->orderBy('id', 'desc')->get();
		return view('page.cctv.index',compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		DB::table('ms_cctv')->insert([
				'title' => Input::get('title'),
				'description' => Input::get('description'),
				'embed' => Input::get('embed'),
				'ms_media_id' => Input::get('ms_media_id'),
				'created_at' => new DateTime(),
				'updated_at' => new DateTime()
			]);
		Session::flash('success','Data berhasil ditambahkan');
		return redirect()->route('vrs-admin.cctv.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['content']=DB::table('ms_cctv')->find($id);
		return view('page.cctv.edit',compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		DB::table('ms_cctv')->where('id', $id)->update([
				'title' => Input::get('title'),
				'description' => Input::get('description'),
				'embed' => Input::get('embed'),
				'ms_media_id' => Input::get('ms_media_id'),
				'updated_at' => new DateTime()
			]);
		return redirect()->route('vrs-admin.cctv.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		DB::table('ms_cctv')->where('id', $id)->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('vrs-admin.cctv.index');
	}
	
}

intigraf_laravel/resources/views/page/cctv/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Edit CCTV
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::model($data['content'],array('action' => ['CCTVController@update',$data['content']->id],'method' => 'PATCH','files' => true)) !!}
					@include('page.cctv.form',['submitText' => 'Perbarui'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/chartjs/Chart.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
</script>
@include('page.scripts.media')
@stop

intigraf_laravel/resources/views/page/cctv/form.blade.php
<div class="form-group">
	{!! Form::label('ms_media_id','Thumbnail : ') !!}
	<a href="javascript:void(0)" class="btn btn-default" onclick="setFeaturedImage()">Pilih Media</a>
	<div class="col-md-12" id="featuredImage">
	</div>
	{!! Form::hidden('ms_media_id',null, ['class' => 'form-control','id' => 'ms_media_id']) !!}
</div>
<div class="form-group">
	{!! Form::label('title','Title : ') !!}
	{!! Form::text('title',null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>
<div class="form-group">
	{!! Form::label('description','Description : ') !!}
	{!! Form::textarea('description',null, ['class' => 'form-control', 'required' => 'required', 'rows' => 3]) !!}
</div>
<div class="form-group">
	{!! Form::label('embed','Embed Script : ') !!}
	{!! Form::textarea('embed',null, ['class' => 'form-control', 'required' => 'required', 'rows' => 3]) !!}
</div>
<div class="form-group">
	{!! Form::submit($submitText,['class' => 'btn btn-info']) !!}
</div>

intigraf_laravel/resources/views/page/cctv/index.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						CCTV
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					<div class="row">
					@include('page.partials.notification')
					</div>
					<div class="row">
						<div class="col-md-3">
							{!! Form::open(array('route' => 'vrs-admin.cctv.store', 'method' => 'post','files' => true)) !!}
							@include('page.errors.list')
							@include('page.cctv.form',['submitText' => 'Tambah'])
							{!! Form::close() !!}
						</div>
						<div class="col-md-9">
							<table class="table" id="dataTables">
								<thead>
									<tr>
										<th class="col-md-1">&nbsp;</th>
										<th class="col-md-9">Nama CCTV</th>
										<th class="col-md-9">Deskripsi</th>
										<th class="col-md-9">Embed Script</th>
										
									</tr>
								</thead>
								<tbody>
									@foreach($data['content'] as $row)
									<tr>
										<td>&nbsp;</td>
										<td>
											{{ $row->title }}
											<div class="action-post-hover">
												<a href="{{route('vrs-admin.cctv.edit',[ $row->id ])}}">edit</a>
												<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('vrs-admin.cctv.delete',[ $row->id ]) !!}" style="color:red;">trash</a>
											</div>
										</td>
										<td>
											{{$row->description}}
										</td>
										<td>{{$row->embed}}</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/chartjs/Chart.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
</script>
@include('page.scripts.media')
@stop