intigraf_laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', 'HomeController@index');
Route::post('/subscribe', 'HomeController@subscribe');
// Route::get('/blogs/{id}{page?}',array('as' => 'home.category', 'uses' => 'HomeController@category'));
Route::get('/212/kategori/{id}/{detail}/{page?}',array('as' => 'home.category', 'uses' => 'HomeController@category'));
Route::get('/news/{id}',array('as' => 'home.post', 'uses' => 'HomeController@post'));
Route::get('/gerai',array('as' => 'home.mitra', 'uses' => 'HomeController@mitra'));
Route::get('/contact', array('as' => 'home.contact', 'uses' => 'HomeController@contact'));
Route::post('/doContact', array('as' => 'home.doContact', 'uses' => 'HomeController@doContact'));
Route::get('/agenda', array('as' => 'home.calendar', 'uses' => 'HomeController@calendar'));

Route::get('/media/korlantas/{id}/{detail}/{idchild?}',array('as' => 'home.portfolio', 'uses' => 'HomeController@portfolio'));
Route::get('/media/type/{id}/{detail}/{idchild?}',array('as' => 'home.type', 'uses' => 'HomeController@portfolioType'));
Route::get('/page/rss/{id}/{page?}',array('as' => 'home.rss', 'uses' => 'HomeController@rss'));
Route::get('/cari',array('as' => 'home.search', 'uses' => 'HomeController@search'));


Route::group(['middleware' => ['auth']], function(){
Route::get('vrs-admin/brosur', 'GeneralController@subscription');
	Route::post('vrs-admin/brosur', 'GeneralController@subscribe');
	Route::resource('vrs-admin/aduan', 'AduanController');
	Route::get('vrs-admin/replyForm/{id}', ['as' => 'vrs-admin.aduan.replyForm', 'uses' => 'AduanController@replyForm']);
	Route::get('vrs-admin/aduan/{id}/delete', ['as' => 'vrs-admin.aduan.delete', 'uses'=>'AduanController@destroys']);
	Route::post('vrs-admin/reply/{id}', ['as' => 'vrs-admin.aduan.reply', 'uses' => 'AduanController@reply']);

	Route::get('vrs-admin/product/getAllAjax',array('as' => 'product.api.getall','uses' => 'ProductController@getAllAjax'));
	Route::get('vrs-admin/product/{product}/delete',array('as'=> 'product.delete','uses' => 'ProductController@destroy'));
	Route::resource('vrs-admin/product', 'ProductController');

	Route::get('vrs-admin/event/getAllAjax',array('as' => 'event.api.getall','uses' => 'EventController@getAllAjax'));
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');
Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'vrs-admin.gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
		Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'vrs-admin.gerai.delete','uses' => 'GeraiController@destroy'));
		Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'vrs-admin.gerai.featured','uses' => 'GeraiController@featured'));
		Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');
	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');
	
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'cctv.delete','uses' => 'CCTVController@destroy'));

	Route::resource('vrs-admin/theme', 'ThemeController');
	Route::get('vrs-admin/club/{club}/delete',array('as'=> 'club.delete','uses' => 'ClubController@destroy'));
	Route::resource('vrs-admin/club', 'ClubController');

	Route::get('vrs-admin/portfolio/enabled/{id}/{menu}',array('as'=> 'portfolio.enabled','uses' => 'PortfolioController@enabled'));
	Route::get('vrs-admin/portfolio/featured/{id}', array('as' => 'portfolio.featured','uses' => 'PortfolioController@featured'));
	Route::get('vrs-admin/portfolio/{menu}/delete',array('as'=> 'portfolio.delete','uses' => 'PortfolioController@destroy'));

	Route::get('vrs-admin/detailportfolio/{menu}/delete',array('as'=> 'detailportfolio.delete','uses' => 'DetailPortfolioController@destroy'));
	Route::resource('vrs-admin/detailportfolio', 'DetailPortfolioController');

	Route::get('vrs-admin/portfolio/getAllData',array('as' => 'portfolio.api.getall','uses' => 'PortfolioController@getAllData'));
	Route::resource('vrs-admin/portfolio', 'PortfolioController');

	Route::get('vrs-admin/menu/{menu}/delete',array('as'=> 'menu.delete','uses' => 'MenuController@destroy'));
	Route::resource('vrs-admin/menu', 'MenuController');
	Route::get('vrs-admin/menu/detail/{menu}/delete',array('as'=> 'menu.detail.delete','uses' => 'MenuDetailController@destroy'));
	Route::get('vrs-admin/menu/detail/getjson',array('as'=> 'menu.detail.getjson','uses' => 'MenuDetailController@getjson'));
	Route::resource('vrs-admin/menu/detail', 'MenuDetailController');

	Route::resource('vrs-admin/ujian', 'UjianController');
	Route::get('vrs-admin/ujian/{ujian}/delete',array('as'=> 'ujian.delete','uses' => 'UjianController@destroy'));

	Route::resource('vrs-admin/soal', 'SoalController');
	Route::get('vrs-admin/soal/{soal}/delete',array('as'=> 'soal.delete','uses' => 'SoalController@destroy'));

	Route::post('vrs-admin/general/upload',array('as' => 'general.upload', 'uses' => 'GeneralController@upload'));
	Route::resource('vrs-admin/general', 'GeneralController');

	Route::get('vrs-admin/contact/enabled/{id}',array('as' => 'contact.enabled', 'uses' => 'ContactController@enabled'));
	Route::get('vrs-admin/contact/{contact}/delete',array('as'=> 'contact.delete','uses' => 'ContactController@destroy'));
	Route::resource('vrs-admin/contact', 'ContactController');
	
	Route::resource('vrs-admin/dailycp', 'DailyCPController');

	Route::get('vrs-admin/rss/getAllAjax',array('as' => 'rss.api.getall','uses' => 'RssController@getAllAjax'));
	Route::get('vrs-admin/rss/{rss}/delete',array('as'=> 'rss.delete','uses' => 'RssController@destroy'));
	Route::resource('vrs-admin/rss', 'RssController');

	Route::get('vrs-admin/social/{social}/delete',array('as'=> 'social.delete','uses' => 'SocialController@destroy'));
	Route::resource('vrs-admin/social', 'SocialController');

	Route::get('vrs-admin/comment/{comment}/delete',array('as'=> 'comment.delete','uses' => 'CommentController@destroy'));
	Route::get('vrs-admin/comment/{comment}/approve/{on}',array('as'=> 'comment.approve','uses' => 'CommentController@approve'));
	Route::resource('vrs-admin/comment','CommentController');

	Route::get('vrs-admin/typeclub/{id}/delete',array('as'=> 'typeclub.delete','uses' => 'TypeClubController@destroy'));
	Route::resource('vrs-admin/typeclub','TypeClubController');

	Route::get('vrs-admin/portfoliocategory/getAllAjax',array('as' => 'portfoliocategory.api.getall','uses' => 'PortfolioCategoryController@getAllAjax'));

	//Route::get('vrs-admin/notification/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/notification/create',array('as'=> 'notification.create','uses' => 'NotificationController@create'));
	Route::resource('vrs-admin/notification', 'NotificationController');
	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');

intigraf_laravel/resources/views/page/postold/create.blade.php
@extends('app')
@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						TAMBAH POST BARU
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::open(array('url' => 'vrs-admin/post','method' => 'post')) !!}
					<div class="col-md-9">
						@include('page.errors.list')
						@include('page.post.form',['submitText' => 'Tambahkan'])
					</div>
					<div class="col-md-3">
						<?php 
						$arrPortfolio = array();
						$arrPortfolio[0] = 'Tidak Ada';
						foreach($data['portfolio'] as $row)
						{
							$arrPortfolio[$row->id] = $row->title;
						}
						?>
						@include('page.post.right-sidebar',['arrPortfolio' => $arrPortfolio])
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')

@endsection

@section('custom-head')

@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/jqueryValidation/jquery.validate.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('plugins/tinymce/js/tinymce/tinymce.min.js')}}"></script>
@include('page.post.script')
@stop

intigraf_laravel/resources/views/page/postold/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						EDIT POST
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::model($data['content'],array('action' => ['PostController@update',$data['content']->id],'method' => 'PATCH')) !!}
					<div class="col-md-9">
						@include('page.errors.list')
						@include('page.post.form',['submitText' => 'Perbarui'])
					</div>
					<div class="col-md-3">
						<?php 
						$arrPortfolio = array();
						$arrPortfolio[0] = 'Tidak Ada';
						foreach($data['portfolio'] as $row)
						{
							$arrPortfolio[$row->id] = $row->title;
						}
						?>
						@include('page.post.right-sidebar',['arrPortfolio' => $arrPortfolio])
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')
@endsection

@section('custom-head')

@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/jqueryValidation/jquery.validate.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('plugins/tinymce/js/tinymce/tinymce.min.js')}}"></script>
 
@include('page.post.script')
@stop

intigraf_laravel/resources/views/page/postold/featured-image.blade.php
		<div class="modal fade" id="mediaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="myModalLabel">Set Featured Image</h4>
					</div>
					<div class="modal-body">
						<div role="tabpanel">
							<ul class="nav nav-tabs" id="mediaTab"  role="tablist">
								<li role="presentation"><a href="#uploadMedia"  aria-controls="uploadMedia" role="tab" data-toggle="tab">Upload</a></li>
								<li role="presentation" class="active"><a href="#listMediaContainer"  aria-controls="listMediaContainer" role="tab" data-toggle="tab">Media</a></li>
							</ul>
						</div>
						<div class="tab-content">
							<div id="uploadMedia" role="tabpanel" class="tab-pane">
								{!! Form::open(array('url' => 'vrs-admin/media/storeAjax','method' => 'post', 'id' => 'mediaUploadForm')) !!}
								<div class="form-group">
									{!! Form::label('file','File : ') !!}
									{!! Form::file('file', ['class' => 'form-control','id' => 'mediaBrowse']) !!}
								</div>
								{!! Form::close() !!}
								<div id='preloader' style='display:none'>
									<span class="glyphicon glyphicon-refresh preloader"></span>
								</div>
							</div>
							<div id="listMediaContainer" role="tabpanel" class="tab-pane active">
								<p>
									<div id="listMedia" class="row">
										
									</div>
								</p>
							</div>
						</div>
						
						
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
						<button type="button" class="btn btn-primary" onclick="setFeatured()">Set Gambar Fitur</button>
					</div>
				</div>
			</div>
		</div>

intigraf_laravel/resources/views/page/postold/form.blade.php
		<div class="form-group">
			{!! Form::label('title','Judul : ') !!}
			{!! Form::text('title',null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('title_eng','Judul (eng): ') !!}
			{!! Form::text('title_eng',null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('description','Deskripsi : ') !!}
			{!! Form::textarea('description',null, ['class' => 'form-control textEditor','id' => 'textEditor']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('eng_description','Description (English) : ') !!}
			{!! Form::textarea('eng_description',null, ['class' => 'form-control textEditor','id' => 'textEditor']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('show_comment','Komentar : ') !!}
			<label>
      			{!! Form::checkbox('show_comment','1',null, ['class' => '','id' => '']) !!} 
    		</label>
			
		</div>
		<div class="form-group">
			{!! Form::submit($submitText,['class' => 'btn btn-info']) !!}
		</div>

intigraf_laravel/resources/views/page/postold/index.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						POST
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<table class="table" id="dataTables">
						<thead>
							<tr>
								<th>&nbsp;</th>
								<th>Judul</th>
								<th>Penulis</th>
								<th>Kategori</th>
								<th>Tag</th>
								<th>Featured</th>
								<th>Tanggal</th>
							</tr>
						</thead>
						<tbody>
							@foreach($data['content'] as $row)
							<?php 
								if($row->user == null)
									continue;
							?>
							<tr>
								<td>&nbsp;</td>
								<td>
									{{ $row->title }}
									<div class="action-post-hover">
										<a href="{!! route('post.edit',[ $row->id ]) !!}" style="color:orange;">edit</a>

 										<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('post.delete',[ $row->id ]) !!}" style="color:red;">trash</a>
									</div>
								</td>
								<td>{{ $row->user->name }}</td>
								<td>
									<?php $category = array(); ?>
									@foreach($row->category as $v)
									<?php array_push($category, $v->title) ?>
									@endforeach
									{!! implode(', ', $category) !!}
								</td>
								<td>
									<?php $tag = array(); ?>
									@foreach($row->tag as $v)
									<?php array_push($tag, $v->title) ?>
									@endforeach
									{!! implode(', ', $tag) !!}
								</td>
								<td>
									<div class="Switch Round {!! $row->featured=='1'?'On':'Off' !!}" data-id="{!! $row->id !!}">
										<div class="Toggle"></div>
									</div>
								</td>
								<td>
									{!! date('d/m/Y',strtotime($row->updated_at)) !!}
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
	$('#dataTables').on('click', '.Switch', function()  {
		var id_post = $(this).data("id");
		setFeatured(id_post);
		$(this).toggleClass('On').toggleClass('Off');
	});
	function setFeatured(id)
	{
		var url = "{{ URL::to('vrs-admin/post/featured') }}/" + id +"";
		$.ajax(url)
		.done(function() {
			
		})
		.fail(function() {
			alert( "error" );
		});
	}
</script>
@stop

intigraf_laravel/resources/views/page/postold/right-sidebar.blade.php
			<div class="panel panel-default">
		  		<div class="panel-heading">Kategori</div>
				<div class="panel-body">
					<div id="listCategory">
					<?php $arrCategory = array(); ?>
					@if(isset($data['content']))
						
						@foreach($data['content']->category as $row)
						<?php array_push($arrCategory, $row->id); ?>
						@endforeach
						
					@endif
			    	@foreach($data['categories'] as $row)
			    		<div class="form-group">
			    			<label>
		    					<input type="checkbox" name="categories[]" {{ in_array($row->id, $arrCategory)?'checked':'' }} value="{!! $row->id !!}"> {!! $row->title !!}
		    				</label>
			    		</div>
			    	@endforeach
			    	</div>
			    	<a href="javascript:void(0)" onclick="addCategory()">+ Tambah Kategori</a>
			    	<div class="col-md-12" id="newCategoryForm">
			    		<div class="form-group">
			    			{!! Form::text('newCategory',null, ['class' => 'form-control','placeholder' => 'Ketikan kategori','id' => 'newCategory']) !!}
			    		</div>
			    		<div class="form-group">
			    			<a href="javascript:void(0)" class="btn btn-default" onclick="postCategory()">Tambah Kategori Baru</a>
			    		</div>
			    	</div>
			  	</div>
			</div>
			<div class="panel panel-default">
		  		<div class="panel-heading">Tag</div>
				<div class="panel-body">
					<div id="listTag" class="row">
					<?php $arrTag = array(); ?>
					@if(isset($data['content']))
						
						@foreach($data['content']->tag as $row)
						<?php array_push($arrTag, $row->id); ?>
						@endforeach
						
					@endif
			    	@foreach($data['tags'] as $row)
			    		<div class="col-md-6">
			    			<label>
		    					<input type="checkbox" name="tags[]" {{ in_array($row->id, $arrTag)?'checked':'' }} value="{!! $row->id !!}"> {!! $row->title !!}
		    				</label>
			    		</div>
			    	@endforeach
			    	</div>
			    	<a href="javascript:void(0)" onclick="addTag()">+ Tambah Tag</a>
			    	<div class="col-md-12" id="newTagForm">
			    		<div class="form-group">
			    			{!! Form::text('newTag',null, ['class' => 'form-control','placeholder' => 'Ketikan tag','id' => 'newTag']) !!}
			    		</div>
			    		<div class="form-group">
			    			<a href="javascript:void(0)" class="btn btn-default" onclick="postTag()">Tambah Tag Baru</a>
			    		</div>
			    	</div>
			  	</div>
			</div>
			<div class="panel panel-default">
		  		<div class="panel-heading">Meta Deskripsi</div>
				<div class="panel-body">
					<div class="form-group">
						{!! Form::textarea('meta_description',null,['class' => 'form-control','rows' => '3']) !!}
					</div>
			  	</div>
			</div>
			<div class="panel panel-default">
		  		<div class="panel-heading">Portfolio Relasi</div>
				<div class="panel-body">
					<div class="form-group">
						{!! Form::select('ms_portfolio_id',$arrPortfolio,null, ['class' => 'form-control']) !!}
					</div>
			  	</div>
			</div>
			<div class="panel panel-default">
		  		<div class="panel-heading">Gambar Fitur</div>
				<div class="panel-body">
					<div class="col-md-12" id="featuredImage">
					
					</div>
					{!! Form::hidden('ms_media_id',isset($data['content'])?$data['content']->ms_media_id:'',['id' => 'ms_media_id']) !!}
					<div class="col-md-12">
						<div class="col-md-6">
				    		<a href="javascript:void(0)" onclick="setFeaturedImage()">+ Set Gambar</a>
				    	</div>
				    	<div class="col-md-6">
				    		<a href="javascript:void(0)" id="mediaUnset" onclick="mediaUnset()" style="color:red;">- Hapus Gambar</a>
				    	</div>
			    	</div>

			  	</div>
			</div>

intigraf_laravel/resources/views/page/postold/script.blade.php
<script>
	$('#newCategoryForm').hide();
	$('#newTagForm').hide();
	tinymce.init(
	{	 
		plugins: [
     "advlist autolink link image lists charmap print preview hr anchor pagebreak code",
     "searchreplace wordcount visualblocks visualchars insertdatetime media nonbreaking",
     "table contextmenu directionality emoticons paste textcolor"
		],
		selector:'.textEditor',
		toolbar: "styleselect formatselect  fontselect fontsizeselect  | ,bold italic underline | blockquote | media | image | alignleft aligncenter alignright alignjustify | outdent indent | bullist numlist | cut copy paste |  undo redo | removeformat subscript superscript",
		image_advtab: true ,
		image_list: "{{ URL::to('/imglist') }}",
		relative_urls: false,
		remove_script_host: false
	});
	function addCategory() {
		$('#newCategoryForm').toggle();
	}
	function postCategory(){
		var title = $('#newCategory').val();
		if(title == '')
			return false;
		$.get("{{ URL::to('vrs-admin/category/storeAjax') }}",
	        {
	          title: title,
	        },
	        function(data,status){
	            if(status=='success')
	            {
	            	var html = "<div class='form-group'><label><input type='checkbox' name='categories[]' checked value='" + data + "'> " + title +"</label></div>";
	            	$('#newCategory').val('');
	            	$('#listCategory').append(html);
	            	console.log(data);
	            }

	        }
        );
	}
	function addTag() {
		$('#newTagForm').toggle();
	}
	function postTag(){
		var title = $('#newTag').val();
		if(title == '')
			return false;
		$.get("{{ URL::to('vrs-admin/tag/storeAjax') }}",
	        {
	          title: title,
	        },
	        function(data,status){
	            if(status=='success')
	            {
	            	var html = "<div class='col-md-6'><label><input type='checkbox' name='tags[]' checked value='" + data + "'> " + title +"</label></div>";
	            	$('#newTag').val('');
	            	$('#listTag').append(html);
	            	console.log(data);
	            }

	        }
        );
	}

</script>
	@if(isset($data['content']) && $data['content']->ms_media_id!='0' )
		@include('page.scripts.media',['featuredImage' => $data['content']->mediaPost->file])
	@else
		@include('page.scripts.media')
	@endif