intigraf_laravel/routes/web.php
Route::get('/page/rss/{id}/{page?}',array('as' => 'home.rss', 'uses' => 'HomeController@rss'));
Route::get('/cari',array('as' => 'home.search', 'uses' => 'HomeController@search'));


Route::group(['middleware' => ['auth']], function(){
Route::get('vrs-admin/brosur', 'GeneralController@subscription');
	Route::post('vrs-admin/brosur', 'GeneralController@subscribe');
	Route::resource('vrs-admin/aduan', 'AduanController');
	Route::get('vrs-admin/replyForm/{id}', ['as' => 'vrs-admin.aduan.replyForm', 'uses' => 'AduanController@replyForm']);
	Route::get('vrs-admin/aduan/{id}/delete', ['as' => 'vrs-admin.aduan.delete', 'uses'=>'AduanController@destroys']);
	Route::post('vrs-admin/reply/{id}', ['as' => 'vrs-admin.aduan.reply', 'uses' => 'AduanController@reply']);

	Route::get('vrs-admin/product/getAllAjax',array('as' => 'product.api.getall','uses' => 'ProductController@getAllAjax'));
	Route::get('vrs-admin/product/{product}/delete',array('as'=> 'product.delete','uses' => 'ProductController@destroy'));
	Route::resource('vrs-admin/product', 'ProductController');

	Route::get('vrs-admin/event/getAllAjax',array('as' => 'event.api.getall','uses' => 'EventController@getAllAjax'));
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');
Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'vrs-admin.gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
		Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'vrs-admin.gerai.delete','uses' => 'GeraiController@destroy'));
		Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'vrs-admin.gerai.featured','uses' => 'GeraiController@featured'));
		Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');
	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');
	
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'cctv.delete','uses' => 'CCTVController@destroy'));

	Route::resource('vrs-admin/theme', 'ThemeController');
	Route::get('vrs-admin/club/{club}/delete',array('as'=> 'club.delete','uses' => 'ClubController@destroy'));
	Route::resource('vrs-admin/club', 'ClubController');

	Route::get('vrs-admin/portfolio/enabled/{id}/{menu}',array('as'=> 'portfolio.enabled','uses' => 'PortfolioController@enabled'));
	Route::get('vrs-admin/portfolio/featured/{id}', array('as' => 'portfolio.featured','uses' => 'PortfolioController@featured'));
	Route::get('vrs-admin/portfolio/{menu}/delete',array('as'=> 'portfolio.delete','uses' => 'PortfolioController@destroy'));

	Route::get('vrs-admin/detailportfolio/{menu}/delete',array('as'=> 'detailportfolio.delete','uses' => 'DetailPortfolioController@destroy'));
	Route::resource('vrs-admin/detailportfolio', 'DetailPortfolioController');

	Route::get('vrs-admin/portfolio/getAllData',array('as' => 'portfolio.api.getall','uses' => 'PortfolioController@getAllData'));
	Route::resource('vrs-admin/portfolio', 'PortfolioController');

	Route::get('vrs-admin/menu/{menu}/delete',array('as'=> 'menu.delete','uses' => 'MenuController@destroy'));
	Route::resource('vrs-admin/menu', 'MenuController');
	Route::get('vrs-admin/menu/detail/{menu}/delete',array('as'=> 'menu.detail.delete','uses' => 'MenuDetailController@destroy'));
	Route::get('vrs-admin/menu/detail/getjson',array('as'=> 'menu.detail.getjson','uses' => 'MenuDetailController@getjson'));
	Route::resource('vrs-admin/menu/detail', 'MenuDetailController');

	Route::resource('vrs-admin/ujian', 'UjianController');
	Route::get('vrs-admin/ujian/{ujian}/delete',array('as'=> 'ujian.delete','uses' => 'UjianController@destroy'));

	Route::resource('vrs-admin/soal', 'SoalController');
	Route::get('vrs-admin/soal/{soal}/delete',array('as'=> 'soal.delete','uses' => 'SoalController@destroy'));

	Route::post('vrs-admin/general/upload',array('as' => 'general.upload', 'uses' => 'GeneralController@upload'));
	Route::resource('vrs-admin/general', 'GeneralController');

	Route::get('vrs-admin/contact/enabled/{id}',array('as' => 'contact.enabled', 'uses' => 'ContactController@enabled'));
	Route::get('vrs-admin/contact/{contact}/delete',array('as'=> 'contact.delete','uses' => 'ContactController@destroy'));
	Route::resource('vrs-admin/contact', 'ContactController');
	
	Route::resource('vrs-admin/dailycp', 'DailyCPController');

	Route::get('vrs-admin/rss/getAllAjax',array('as' => 'rss.api.getall','uses' => 'RssController@getAllAjax'));
	Route::get('vrs-admin/rss/{rss}/delete',array('as'=> 'rss.delete','uses' => 'RssController@destroy'));
	Route::resource('vrs-admin/rss', 'RssController');

	Route::get('vrs-admin/social/{social}/delete',array('as'=> 'social.delete','uses' => 'SocialController@destroy'));
	Route::resource('vrs-admin/social', 'SocialController');

	Route::get('vrs-admin/comment/{comment}/delete',array('as'=> 'comment.delete','uses' => 'CommentController@destroy'));
	Route::get('vrs-admin/comment/{comment}/approve/{on}',array('as'=> 'comment.approve','uses' => 'CommentController@approve'));
	Route::resource('vrs-admin/comment','CommentController');

	Route::get('vrs-admin/typeclub/{id}/delete',array('as'=> 'typeclub.delete','uses' => 'TypeClubController@destroy'));
	Route::resource('vrs-admin/typeclub','TypeClubController');

	Route::get('vrs-admin/portfoliocategory/getAllAjax',array('as' => 'portfoliocategory.api.getall','uses' => 'PortfolioCategoryController@getAllAjax'));

	//Route::get('vrs-admin/notification/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/notification/create',array('as'=> 'notification.create','uses' => 'NotificationController@create'));
	Route::resource('vrs-admin/notification', 'NotificationController');
	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');
	Route::get('vrs-admin/media/getMedia/{name}','MediaController@getMedia');
	Route::get('vrs-admin/media/{media}/delete',array('as'=> 'media.delete','uses' => 'MediaController@destroy'));
	
	Route::resource('vrs-admin/media', 'MediaController');
	
	Route::get('vrs-admin/file/getMedia/{name}','FileController@getMedia');
	//Route::post('vrs-admin/file/create',array('as'=> 'file.create','uses' => 'FileController@create'));
	Route::get('vrs-admin/file/{file}/delete',array('as'=> 'file.delete','uses' => 'FileController@destroy'));
	Route::get('vrs-admin/file/featured/{id}', array('as' => 'file.featured','uses' => 'FileController@featured'));
	Route::resource('vrs-admin/file', 'FileController');
	Route::resource('vrs-admin/log', 'LogController');

	Route::get('vrs-admin/video/getMedia/{name}','VideoController@getMedia');
	Route::get('vrs-admin/video/{video}/delete',array('as'=> 'video.delete','uses' => 'VideoController@destroy'));
	Route::get('vrs-admin/video/featured/{id}', array('as' => 'video.featured','uses' => 'VideoController@featured'));
	Route::resource('vrs-admin/video', 'VideoController');

	Route::any('/imglist', ['as'=>'imglist', 'uses'=>'FileBrowserController@imageList']);
		//Image upload

		Route::any('/upload', [ 'uses' =>'FileBrowserController@index']);
});

Route::get('read/{id}', 'PostController@show');
Route::get('/map', 'HomeController@map');

intigraf_laravel/app/Club.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model {

	protected $table = 'ms_clubs';
	protected $fillable = array('name','city','reward','photo','ms_type_club_id');
	public $timestamps = true;
	public function logs()
	    {
	        return $this->morphMany('App\Log', 'logable');
	    }
	public function typeClub()
    {
    	return $this->belongsTo('App\TypeClub', 'ms_type_club_id', 'id');
    }
}

intigraf_laravel/app/Http/Controllers/ClubController.php
<?php namespace App\Http\Controllers;
/*
lapantiga.com | Web & Mobile App Developer. Jl. Gubeng Kertajaya 9C no.27 A Surabaya - Indonesia, +62.856.3437.495 */

use App\Club;
use App\Http\Controllers\BasicController;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\ClubRequest;
use Illuminate\Http\Request;
use Session;
use Image;
use File;

class ClubController extends BasicController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	protected $path;
	function __construct() {
		$this->path = 'upload/member/';
	}
	public function index()
	{
		$data['content'] = Club::orderBy('created_at')->get();
		return view('page.club.index',compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$data['typeclub'] = \App\TypeClub::lists('name','id');
		return view('page.club.create', compact('data'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(ClubRequest $request)
	{
		$data = new Club;
		$data->name = $request->input('name');
		$data->city = $request->input('city');
		$data->reward = $request->input('reward');
		$data->ms_type_club_id = $request->input('ms_type_club_id');
		if ($request->hasFile('photo'))
		{
		    $file = $request->file('photo');
			$extension = $file->getClientOriginalExtension();
			$fileName = 'user_'.date('Ymd_Hsi').'.'.$extension;
			$file->move($this->path,$fileName);
			// $data->mime = $file->getClientMimeType();
			$img = Image::make($this->path.$fileName);
			$img->resize(200, 200);
			$img->save($this->path.$fileName, 60);
			$data->photo = $fileName;
		}
		$data->save();
		$log = array();
		$log['action'] = 'insert';
		$log['name'] = $request->input('name');
		$data->logs()->save($this->log($log));

		Session::flash('success','Data berhasil ditambahkan');
		return redirect()->route('vrs-admin.club.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['typeclub'] = \App\TypeClub::lists('name','id');
		$data['content'] = Club::find($id);
		return view('page.club.edit',compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(ClubRequest $request, $id)
	{
		$data = Club::find($id);
		
		$data->name = $request->input('name');
		$data->city = $request->input('city');
		$data->reward = $request->input('reward');
		$data->ms_type_club_id = $request->input('ms_type_club_id');
		if ($request->hasFile('photo'))
		{
		    $file = $request->file('photo');
			$extension = $file->getClientOriginalExtension();
			$fileName = 'user_'.date('Ymd_Hsi').'.'.$extension;

			$log = array();
			$log['action'] = 'update';
			$log['name'] = $data->photo.' - '.$fileName;
			$data->logs()->save($this->log($log));


			$file->move($this->path,$fileName);
			$img = Image::make($this->path.$fileName);
			$img->resize(200, 200);
			$img->save($this->path.$fileName, 60);
			if(File::exists('upload/member/'.$data->photo))
			{
				File::delete('upload/member/'.$data->photo);
			}

			// $data->mime = $file->getClientMimeType();
			$data->photo = $fileName;
		}else{
			$log = array();
			$log['action'] = 'update';
			$log['name'] = $data->name;
			$data->logs()->save($this->log($log));
		}
		$data->save();

		Session::flash('success','Data berhasil diperbarui');
		return redirect()->route('vrs-admin.club.index');
	}



	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$data = Club::find($id);
		$log = array();
		$log['action'] = 'delete';
		$log['name'] = $data->name;
		$data->logs()->save($this->log($log));
		if(File::exists('upload/member/'.$data->photo))
			{
				File::delete('upload/member/'.$data->photo);
			}

		$data->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('vrs-admin.club.index');
	}
	public function enabled($id=null)
	{
		if(empty($id))
			return;
		$data = Club::where('featured','1')->first();
		if(!empty($data))
		{
			$data->featured = 0;
			$data->save();
		}
		$data = Club::find($id);
		$data->featured = '1';
		$data->save();
		return;
	}

}

intigraf_laravel/resources/views/page/club/create.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Tambah Member
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::open(['route'=>'vrs-admin.club.store', 'method' => 'POST', 'files' => 'true']) !!}
					@include('page.club.form',['buttonSubmit' => 'Tambah'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

intigraf_laravel/resources/views/page/club/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Edit Member
					</h3>                                    
				</div>
				<div class="box-body">
				{!! Form::model($data['content'], ['route'=>['vrs-admin.club.update', $data['content']->id], 'method' => 'PATCH', 'files' => 'true']) !!}
					@include('page.club.form',['buttonSubmit' => 'Perbarui'])
				{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

intigraf_laravel/resources/views/page/club/form.blade.php
					@include('page.errors.list')
					<div class="form-group col-md-12">
						{!! Form::label('name','Nama : ') !!}
						{!! Form::text('name',null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group col-md-12">
						{!! Form::label('ms_type_club_id','Tipe Reward : ') !!}
						{!! Form::select('ms_type_club_id', $data['typeclub'], null, array('class' => 'form-control')
						) !!}
					</div>
					<div class="form-group">
						{!! Form::label('photo','Photo: ') !!}
						<div class="col-md-12" id="featuredImage">
						@if(isset($data['content']->photo))
							{!! HTML::image(asset('upload/member/'.$data['content']->photo),'',['class' => 'col-md-5 img-thumbnail']) !!}
						@endif
						</div>
						{!! Form::file('photo', ['class' => 'form-control']) !!}
						
					</div>
					<div class="form-group col-md-12">
						{!! Form::label('city','Kota : ') !!}
						{!! Form::text('city',null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group col-md-12">
						{!! Form::label('reward','Reward : ') !!}
						{!! Form::textarea('reward',null, ['class' => 'form-control','rows'=>'3']) !!}
					</div>
					
					<div class="form-group col-md-12">
						{!! Form::submit($buttonSubmit,['class' => 'btn btn-info']) !!}
					</div>

intigraf_laravel/resources/views/page/club/index.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						MEMBER {!! HTML::link(route('vrs-admin.club.create'),'Tambah Baru',['class' => 'btn btn-default btn-add-new']) !!}
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<div class="row">
						<div class="col-md-10">
							<table class="table" id="dataTables">
								<thead>
									<tr>
										<th>&nbsp;</th>
										<th>Nama</th>
										<th>Tipe Club</th>
										<th>Kota</th>
										<th>Reward</th>
										<th>Photo</th>
									</tr>
								</thead>
								<tbody>
									@foreach($data['content'] as $row)
									<tr>
										<td>&nbsp;</td>
										<td>
											{{ $row->name }}
											<div class="action-post-hover">
												{!! HTML::link(route('vrs-admin.club.edit',[ $row->id ]),'edit') !!}
												<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('vrs-admin.club.delete',[ $row->id ]) !!}" style="color:red;">trash</a>
											</div>
										</td>
										<td><b>{{ ucfirst($row->typeclub->name) }}</b> </td>
										<td>{{ $row->city }}</td>
										<td>
										{{ $row->reward }}</td>
										<td>
											{{ $row->address }}
										</td>
										<td>
											@if(isset($row->photo))
							{!! HTML::image(asset('upload/member/'.$row->photo),'',['class' => 'col-md-5 img-thumbnail']) !!}
						@endif
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/dataTables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/dataTables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
	$('.radio-featured').click(function() {
		$('.radio-featured').prop('checked',false);
		$(this).prop('checked',true);			
		var id = $(this).val();
		var url = "{{ URL::to('vrs-admin/club/enabled') }}/" + id +"";
		$.ajax(url)
		.done(function() {
			
		})
		.fail(function() {
			alert( "error" );
		});
	})
</script>
@stop