intigraf_laravel/routes/web.php
Route::get('vrs-admin/brosur', 'GeneralController@subscription');
	Route::post('vrs-admin/brosur', 'GeneralController@subscribe');
	Route::resource('vrs-admin/aduan', 'AduanController');
	Route::get('vrs-admin/replyForm/{id}', ['as' => 'vrs-admin.aduan.replyForm', 'uses' => 'AduanController@replyForm']);
	Route::get('vrs-admin/aduan/{id}/delete', ['as' => 'vrs-admin.aduan.delete', 'uses'=>'AduanController@destroys']);
	Route::post('vrs-admin/reply/{id}', ['as' => 'vrs-admin.aduan.reply', 'uses' => 'AduanController@reply']);

	Route::get('vrs-admin/product/getAllAjax',array('as' => 'product.api.getall','uses' => 'ProductController@getAllAjax'));
	Route::get('vrs-admin/product/{product}/delete',array('as'=> 'product.delete','uses' => 'ProductController@destroy'));
	Route::resource('vrs-admin/product', 'ProductController');

	Route::get('vrs-admin/event/getAllAjax',array('as' => 'event.api.getall','uses' => 'EventController@getAllAjax'));
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');
Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'vrs-admin.gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
		Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'vrs-admin.gerai.delete','uses' => 'GeraiController@destroy'));
		Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'vrs-admin.gerai.featured','uses' => 'GeraiController@featured'));
		Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');
	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');
	
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'cctv.delete','uses' => 'CCTVController@destroy'));

	Route::resource('vrs-admin/theme', 'ThemeController');
	Route::get('vrs-admin/club/{club}/delete',array('as'=> 'club.delete','uses' => 'ClubController@destroy'));
	Route::resource('vrs-admin/club', 'ClubController');

	Route::get('vrs-admin/portfolio/enabled/{id}/{menu}',array('as'=> 'portfolio.enabled','uses' => 'PortfolioController@enabled'));
	Route::get('vrs-admin/portfolio/featured/{id}', array('as' => 'portfolio.featured','uses' => 'PortfolioController@featured'));
	Route::get('vrs-admin/portfolio/{menu}/delete',array('as'=> 'portfolio.delete','uses' => 'PortfolioController@destroy'));

	Route::get('vrs-admin/detailportfolio/{menu}/delete',array('as'=> 'detailportfolio.delete','uses' => 'DetailPortfolioController@destroy'));
	Route::resource('vrs-admin/detailportfolio', 'DetailPortfolioController');

	Route::get('vrs-admin/portfolio/getAllData',array('as' => 'portfolio.api.getall','uses' => 'PortfolioController@getAllData'));
	Route::resource('vrs-admin/portfolio', 'PortfolioController');

	Route::get('vrs-admin/menu/{menu}/delete',array('as'=> 'menu.delete','uses' => 'MenuController@destroy'));
	Route::resource('vrs-admin/menu', 'MenuController');
	Route::get('vrs-admin/menu/detail/{menu}/delete',array('as'=> 'menu.detail.delete','uses' => 'MenuDetailController@destroy'));
	Route::get('vrs-admin/menu/detail/getjson',array('as'=> 'menu.detail.getjson','uses' => 'MenuDetailController@getjson'));
	Route::resource('vrs-admin/menu/detail', 'MenuDetailController');

	Route::resource('vrs-admin/ujian', 'UjianController');
	Route::get('vrs-admin/ujian/{ujian}/delete',array('as'=> 'ujian.delete','uses' => 'UjianController@destroy'));

	Route::resource('vrs-admin/soal', 'SoalController');
	Route::get('vrs-admin/soal/{soal}/delete',array('as'=> 'soal.delete','uses' => 'SoalController@destroy'));

	Route::post('vrs-admin/general/upload',array('as' => 'general.upload', 'uses' => 'GeneralController@upload'));
	Route::resource('vrs-admin/general', 'GeneralController');

	Route::get('vrs-admin/contact/enabled/{id}',array('as' => 'contact.enabled', 'uses' => 'ContactController@enabled'));
	Route::get('vrs-admin/contact/{contact}/delete',array('as'=> 'contact.delete','uses' => 'ContactController@destroy'));
	Route::resource('vrs-admin/contact', 'ContactController');
	
	Route::resource('vrs-admin/dailycp', 'DailyCPController');

	Route::get('vrs-admin/rss/getAllAjax',array('as' => 'rss.api.getall','uses' => 'RssController@getAllAjax'));
	Route::get('vrs-admin/rss/{rss}/delete',array('as'=> 'rss.delete','uses' => 'RssController@destroy'));
	Route::resource('vrs-admin/rss', 'RssController');

	Route::get('vrs-admin/social/{social}/delete',array('as'=> 'social.delete','uses' => 'SocialController@destroy'));
	Route::resource('vrs-admin/social', 'SocialController');

	Route::get('vrs-admin/comment/{comment}/delete',array('as'=> 'comment.delete','uses' => 'CommentController@destroy'));
	Route::get('vrs-admin/comment/{comment}/approve/{on}',array('as'=> 'comment.approve','uses' => 'CommentController@approve'));
	Route::resource('vrs-admin/comment','CommentController');

	Route::get('vrs-admin/typeclub/{id}/delete',array('as'=> 'typeclub.delete','uses' => 'TypeClubController@destroy'));
	Route::resource('vrs-admin/typeclub','TypeClubController');

	Route::get('vrs-admin/portfoliocategory/getAllAjax',array('as' => 'portfoliocategory.api.getall','uses' => 'PortfolioCategoryController@getAllAjax'));

	//Route::get('vrs-admin/notification/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/notification/create',array('as'=> 'notification.create','uses' => 'NotificationController@create'));
	Route::resource('vrs-admin/notification', 'NotificationController');
	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');
	Route::get('vrs-admin/media/getMedia/{name}','MediaController@getMedia');
	Route::get('vrs-admin/media/{media}/delete',array('as'=> 'media.delete','uses' => 'MediaController@destroy'));
	
	Route::resource('vrs-admin/media', 'MediaController');
	
	Route::get('vrs-admin/file/getMedia/{name}','FileController@getMedia');
	//Route::post('vrs-admin/file/create',array('as'=> 'file.create','uses' => 'FileController@create'));
	Route::get('vrs-admin/file/{file}/delete',array('as'=> 'file.delete','uses' => 'FileController@destroy'));
	Route::get('vrs-admin/file/featured/{id}', array('as' => 'file.featured','uses' => 'FileController@featured'));
	Route::resource('vrs-admin/file', 'FileController');
	Route::resource('vrs-admin/log', 'LogController');

	Route::get('vrs-admin/video/getMedia/{name}','VideoController@getMedia');
	Route::get('vrs-admin/video/{video}/delete',array('as'=> 'video.delete','uses' => 'VideoController@destroy'));
	Route::get('vrs-admin/video/featured/{id}', array('as' => 'video.featured','uses' => 'VideoController@featured'));
	Route::resource('vrs-admin/video', 'VideoController');

	Route::any('/imglist', ['as'=>'imglist', 'uses'=>'FileBrowserController@imageList']);
		//Image upload

		Route::any('/upload', [ 'uses' =>'FileBrowserController@index']);
});

Route::get('read/{id}', 'PostController@show');
Route::get('/map', 'HomeController@map');
Route::post('/adukan', ['as' => 'home.adukan', 'uses' => 'HomeController@adukan']);

Route::get('post/search', 'PostController@search');
// Auth::routes();
Route::group(['middleware' => ['web']], function() {

// Login Routes...

intigraf_laravel/app/Menu.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model {

	protected $table = 'ms_menu';
	protected $fillable = array('code','title');
	public $timestamps = true;

	public function menuDetail()
	{
		return $this->hasMany('App\MenuDetail','ms_menu_id','id')->orderBy('order','asc');
	}
	public function logs()
    {
        return $this->morphMany('App\Log', 'logable');
    }
}

intigraf_laravel/app/MenuType.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class MenuType extends Model {

	protected $table = 'ms_menu_types';
	protected $fillable = array('code','title');
	public $timestamps = false;

	public function menuDetail()
	{
		return $this->hasMany('App\MenuDetail','ms_menu_type_id','id');
	}
}

intigraf_laravel/app/Http/Controllers/MenuController.php
<?php namespace App\Http\Controllers;
/*
lapantiga.com | Web & Mobile App Developer. Jl. Gubeng Kertajaya 9C no.27 A Surabaya - Indonesia, +62.856.3437.495 */

use App\Http\Controllers\BasicController;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\MenuRequest;
use App\Menu;
use App\MenuType;
use Illuminate\Http\Request;
use Session;

class MenuController extends BasicController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$data['content'] = Menu::with('menuDetail')->get();
		return view('page.menu.index',compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('page.menu.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(MenuRequest $request)
	{
		$data = Menu::create($request->all());

		$log = array();
		$log['action'] = 'insert';
		$log['name'] = $request->input('title');
		$data->logs()->save($this->log($log));

		Session::flash('success','Data berhasil ditambahkan');

		return redirect()->route('vrs-admin.menu.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$data['content'] = Menu::with('menuDetail')->find($id);
		$data['menu_type'] = MenuType::all();
		return view('page.menu.details',compact('data'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['content'] = Menu::find($id);
		return view('page.menu.edit',compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(MenuRequest $request, $id)
	{
		$data = Menu::find($id);
		$data->update($request->all());
		$log = array();
		$log['action'] = 'update';
		$log['name'] = $request->input('title');
		$data->logs()->save($this->log($log));

		Session::flash('success','Data berhasil diperbarui');
		return redirect()->route('vrs-admin.menu.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$data = Menu::with('menuDetail')->find($id);
		foreach ($data->menuDetail as $row) {
			$row->delete();
		}
		$log = array();
		$log['action'] = 'delete';
		$log['name'] = $data->title;
		$data->logs()->save($this->log($log));

		$data->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('vrs-admin.menu.index');
	}
}

intigraf_laravel/resources/views/page/menu/create.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Tambah Menu Baru
					</h3>                                    
				</div>
				<div class="box-body">
					
					{!! Form::open(array('route' => 'vrs-admin.menu.store', 'method' => 'POST')) !!}
					@include('page.menu.form',['buttonSubmit' => 'Tambah'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

intigraf_laravel/resources/views/page/menu/details.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						MENU <em><strong> {{  $data['content']->title }} </strong></em>
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<div class="col-md-5">
						<h5>Tambah Detail Menu Baru</h5>
						{!! Form::open(['route'=>'vrs-admin.menu.detail.store', 'method' => 'POST']) !!}
						<?php
						$menuId = $data['content']->id;
						$arrMenuDetail = array();
						$arrMenuDetail[0] = 'Tidak Ada';
						foreach($data['content']->menuDetail as $row)
						{
							$arrMenuDetail[$row->id] = $row->title;
						}
						$arrMenuType = array();
						foreach($data['menu_type'] as $row)
						{
							$arrMenuType[$row->id] = $row->title;
						}
						?>
						@include('page.menu.form-detail',['buttonSubmit' => 'Tambahkan','arrMenuDetail' => $arrMenuDetail])
						{!! Form::close() !!}
					</div>
					<div class="col-md-7">
						<div class="row">
							<p><b>Daftar Detail Menu</b></p>
						</div>
						<table class="table" id="dataTables">
							<thead>
								<tr>
									<th>&nbsp;</th>
									<th>Judul</th>
									<th>Kode</th>
								</tr>
							</thead>
							<tbody>
								@foreach($data['content']->menuDetail as $row)
								<tr>
									<td>&nbsp;</td>
									<td>
										{{ $row->title }}
										<div class="action-post-hover">
											<a href="{{route('vrs-admin.menu.detail.edit',[ $row->id ])}}">edit</a>
											<a href="{{route('vrs-admin.menu.detail.delete',[ $row->id ])}}" style="color:red">trash</a>
										</div>
									</td>
									<td>
										{{ $row->code }}
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>		

@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#category-container').hide();

	$(function () {
		   // your code goes here
		   var tipe = $('#ms_menu_type_id').val();
		   categoryType(tipe);
		});
	$('#ms_menu_type_id').change(function(){
		var tipe = $('#ms_menu_type_id').val();
		categoryType(tipe);
	});
	function categoryType(tipe){
		switch(tipe)
		{
			case '1':
			$.ajax(
			{
				url:"{{ route('vrs-admin.category.api.getall') }}",
				type: "GET",
				data:{
					title: tipe
				}
			}).done(function(data,status){
				if(status=='success')
				{	
					console.log(data);
					var content = '';
					$.each(data, function(key, value){
						content += "<div class='col-md-6'><label><input type='radio' name='custom' value='" + data[key].id +"' /> "+ data[key].title +"</label></div>";
					});
					var html = "<div class='form-group'>"+ content +"</div>";
					$('#menu_type_container').empty();
					$('#menu_type_container').html(html);
				}
			});
			break;
			case '2':
			$.ajax(
			{
				url:"{{ route('vrs-admin.post.api.getall') }}",
				type: "GET",
				data:{
					title: tipe
				}
			}).done(function(data,status){
				if(status=='success')
				{	
					console.log(data);
					var content = '';
					$.each(data, function(key, value){
						var str = data[key].title;
						content += "<div class='col-md-6'><label><input type='radio' name='custom' value='" + data[key].id +"' /> "+ str.substring(0,15) + "..." +"</label></div>";
					});
					var html = "<div class='form-group'>"+ content +"</div>";
					$('#menu_type_container').empty();
					$('#menu_type_container').html(html);
				}
			});
			break;
			case '3':
			$.ajax(
			{
				url:"{{ route('vrs-admin.portfolio.api.getall') }}",
				type: "GET",
				data:{
					title: tipe
				}
			}).done(function(data,status){
				console.log(status);
				if(status=='success')
				{	
					console.log(data);
					var content = '';
					$.each(data, function(key, value){
						var str = data[key].title;
						content += "<div class='col-md-6'><label><input type='radio' name='custom' value='" + data[key].id +"' /> "+ str.substring(0,15) + "..." +"</label></div>";
					});
					var html = "<div class='form-group'>"+ content +"</div>";
					$('#menu_type_container').empty();
					$('#menu_type_container').html(html);
				}
			});
			break;
			case '4':
			$.ajax(
			{
				url:"{{ route('vrs-admin.rss.api.getall') }}",
				type: "GET",
				data:{
					title: tipe
				}
			}).done(function(data,status){
				console.log(status);
				if(status=='success')
				{	
					console.log(data);
					var content = '';
					$.each(data, function(key, value){
						var str = data[key].title;
						content += "<div class='col-md-6'><label><input type='radio' name='custom' value='" + data[key].id +"' /> "+ str.substring(0,15) + "..." +"</label></div>";
					});
					var html = "<div class='form-group'>"+ content +"</div>";
					$('#menu_type_container').empty();
					$('#menu_type_container').html(html);
				}
			});
			break;
			case '5' :
			$('#menu_type_container').empty();
			var html = "<div class='col-md-12'><label for='custom'>Link : </label>";
			html += "<input id='custom' type='text' class='form-control' name='custom' placeholder='ketikan link. (Misal: http://innvaderstudio.com)' /><br></div>";
			$('#menu_type_container').html(html);
			break;
			case '6' :
			$('#menu_type_container').empty();
			$('#menu_type_container').html(html);
			break;
			case '7' :
			$('#menu_type_container').empty();
			$('#menu_type_container').html(html);
			break;
			case '8' :
			$('#menu_type_container').empty();
			$('#menu_type_container').html(html);
			break;
			case '9' :
			$.ajax(
			{
				url:"{{ route('vrs-admin.portfoliocategory.api.getall') }}",
				type: "GET",
				data:{
					title: tipe
				}
			}).done(function(data,status){
				console.log(status);
				if(status=='success')
				{	
					console.log(data);
					var content = '';
					$.each(data, function(key, value){
						var str = data[key].name;
						content += "<div class='col-md-6'><label><input type='radio' name='custom' value='" + data[key].id +"' /> "+ str.substring(0,15) + "..." +"</label></div>";
					});
					var html = "<div class='form-group'>"+ content +"</div>";
					$('#menu_type_container').empty();
					$('#menu_type_container').html(html);
				}
			});
			break;
		}
	}
</script>
@stop

intigraf_laravel/resources/views/page/menu/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Edit Baru
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::model($data['content'],array('action' => ['MenuController@update',$data['content']->id], 'method' => 'PATCH')) !!}
					@include('page.menu.form',['buttonSubmit' => 'Perbarui'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

intigraf_laravel/resources/views/page/menu/form-detail.blade.php
					<div class="form-group">
						{!! Form::label('title','Nama : ') !!}
						{!! Form::text('title',null, ['class' => 'form-control']) !!}
						{!! Form::hidden('ms_menu_id',$menuId, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('code','Kode : ') !!}
						{!! Form::text('code',null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('parent_id','Parent : ') !!}
						{!! Form::select('parent_id',$arrMenuDetail,null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('ms_menu_type_id','Tipe : ') !!}
						{!! Form::select('ms_menu_type_id',$arrMenuType,null, ['class' => 'form-control','id' => 'ms_menu_type_id']) !!}
					</div>
					<div class="form group">
						<div id="menu_type_container" class="row">
							@if(isset($data['detail']))
							@if($data['content']->ms_menu_type_id !='5')
							@foreach($data['detail'] as $row)
							<div class='col-md-6'>
								<label>

								{!! Form::radio('custom', $row->id, null) !!} {{ substr($row->title,0,15) }}...
								
									
								</label>
							</div>
							@endforeach
							@else
								<div class="col-md-12">
									<label for='custom'>Link : </label>
									<input id='custom' type='text' class='form-control' name='custom' placeholder='ketikan link. (Misal: http://innvaderstudio.com)' value="{{ $data['content']->custom }}" /><br>
								</div>
							@endif
							@endif
						</div>
						<div id="category-container">
							
						</div>
					</div>
					<div class="form-group">
						{!! Form::submit($buttonSubmit,['class' => 'btn btn-info']) !!}
					</div>

intigraf_laravel/resources/views/page/menu/form.blade.php
					<div class="form-group">
						{!! Form::label('title','Nama : ') !!}
						{!! Form::text('title',null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						{!! Form::label('code','Kode : ') !!}
						{!! Form::text('code',null, ['class' => 'form-control']) !!}
					</div>
					<div class="form-group">
						{!! Form::submit($buttonSubmit,['class' => 'btn btn-info']) !!}
					</div>

intigraf_laravel/resources/views/page/menu/index.blade.php
@extends('app')
@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						MENU
						<a href="{{route('vrs-admin.menu.create')}}" class="btn btn-default btn-add-new">Tambah baru</a>
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<table class="table" id="dataTables">
						<thead>
							<tr>
								<th>&nbsp;</th>
								<th>Judul</th>
								<th>Kode</th>
							</tr>
						</thead>
						<tbody>
							@foreach($data['content'] as $row)
							<tr>
								<td>&nbsp;</td>
								<td>
									<a href="{{route('vrs-admin.menu.show', [$row->id])}}">{{$row->title}}</a>
									<div class="action-post-hover">
										<a href="{{route('vrs-admin.menu.show',[$row->id])}}">details</a>
										<a href="{{route('vrs-admin.menu.edit',[ $row->id ])}}">edit</a>
										<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('vrs-admin.menu.delete',[ $row->id ]) !!}" style="color:red;">trash</a>
									</div>
								</td>
								<td>
									{{ $row->code }}
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
</script>
@stop